app:
  image: nodeapp
  ports:
    - "8080:8080"
  links:
    - db
db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes_from:
      - app-db-data

app-db-data:  
  image: cogniteev/echo
  command: echo 'Data Container for postgres'
  volumes:
    - /var/lib/postgres/data