version: "3"
services:
  app:
    image: nodeapp
    ports:
      - "8080:8080"
    environment:
     user: postgres
     host: 10.236.22.236
     port: 5432
     database: TechPOC
     password: root